# Generated by Django 3.0.4 on 2020-09-22 18:10

import Personalize.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tort', models.ImageField(blank=True, null=True, upload_to='products/custom/')),
                ('description', models.TextField(default='')),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField(validators=[Personalize.validators.valid_date])),
            ],
        ),
    ]
