# Generated by Django 3.0.4 on 2020-05-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalize', '0002_auto_20200515_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='tort',
            field=models.ImageField(blank=True, null=True, upload_to='products/custom/'),
        ),
    ]
