# Generated by Django 3.0.4 on 2020-09-25 16:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personalize', '0002_customorder_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='tort',
        ),
        migrations.AlterField(
            model_name='customorder',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
