# Generated by Django 3.0.4 on 2020-07-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalize', '0008_auto_20200622_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='tort',
            field=models.ImageField(blank=True, null=True, upload_to='products/custom/'),
        ),
    ]
