# Generated by Django 3.0.4 on 2020-07-03 13:47

import Personalize.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalize', '0009_auto_20200703_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='date',
            field=models.DateField(validators=[Personalize.validators.valid_date]),
        ),
    ]
