# Generated by Django 3.0.4 on 2020-09-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField(unique=True)),
                ('nume', models.CharField(max_length=50)),
                ('pret', models.FloatField()),
                ('descr', models.TextField()),
                ('sum', models.IntegerField(default=0, editable=False)),
                ('number', models.IntegerField(default=0, editable=False)),
                ('finalrating', models.FloatField(default=0, editable=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/img/')),
                ('measure_unit', models.CharField(default='kg', max_length=5)),
            ],
        ),
    ]
