# Generated by Django 3.0.4 on 2020-04-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
                ('nume', models.CharField(max_length=50)),
                ('pret', models.FloatField()),
                ('descr', models.TextField()),
            ],
        ),
    ]
