# Generated by Django 3.0.4 on 2020-05-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='final_rating',
            field=models.FloatField(default=1.0),
        ),
    ]
