# Generated by Django 3.0.4 on 2020-05-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_produs_final_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='final_rating',
        ),
        migrations.AddField(
            model_name='produs',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='produs',
            name='sum',
            field=models.IntegerField(default=1),
        ),
    ]
