# Generated by Django 3.0.4 on 2020-05-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_auto_20200507_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='finalrating',
            field=models.FloatField(default=1),
        ),
    ]
