# Generated by Django 3.0.4 on 2020-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_produs_finalrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='finalrating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produs',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produs',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
