# Generated by Django 3.0.4 on 2020-05-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_produs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
