# Generated by Django 3.0.4 on 2020-05-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0007_auto_20200511_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/img/'),
        ),
    ]
