# Generated by Django 3.0.4 on 2020-07-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0008_auto_20200511_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='finalrating',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='produs',
            name='number',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='produs',
            name='sum',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
