# Generated by Django 3.0.4 on 2020-07-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0009_auto_20200707_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='measure_unit',
            field=models.CharField(default='kg', max_length=10),
        ),
    ]
