# Generated by Django 3.0.4 on 2020-07-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0010_produs_measure_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='measure_unit',
        ),
        migrations.AlterField(
            model_name='produs',
            name='finalrating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produs',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produs',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
