# Generated by Django 3.0.4 on 2020-08-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0012_produs_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='finalrating',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='produs',
            name='number',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='produs',
            name='sum',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
