# Generated by Django 3.0.4 on 2020-08-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0014_auto_20200825_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='ident',
            field=models.IntegerField(auto_created=True, editable=False, unique=True),
        ),
    ]
