# Generated by Django 3.0.4 on 2020-08-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0015_auto_20200825_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='ident',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
