# Generated by Django 3.0.4 on 2020-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comm', '0004_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
