# Generated by Django 3.0.4 on 2020-05-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comm', '0010_auto_20200507_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(),
        ),
    ]
