# Generated by Django 3.0.4 on 2020-05-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comm', '0011_auto_20200510_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
