# Generated by Django 3.0.4 on 2020-05-14 18:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Comm', '0012_auto_20200514_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 14, 18, 50, 6, 780093, tzinfo=utc)),
        ),
    ]
