# Generated by Django 3.0.4 on 2020-05-15 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Comm', '0013_auto_20200514_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 15, 17, 29, 8, 398676, tzinfo=utc)),
        ),
    ]
