# Generated by Django 3.0.4 on 2020-05-15 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Comm', '0014_auto_20200515_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 15, 17, 30, 2, 609008, tzinfo=utc)),
        ),
    ]
