# Generated by Django 3.0.4 on 2020-05-15 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Comm', '0015_auto_20200515_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 15, 19, 7, 53, 880633, tzinfo=utc)),
        ),
    ]
