# Generated by Django 3.0.4 on 2020-05-17 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Comm', '0019_auto_20200515_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 19, 5, 40, 508621, tzinfo=utc)),
        ),
    ]
