# Generated by Django 3.0.4 on 2020-05-18 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Comm', '0020_auto_20200517_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 18, 19, 53, 8, 526336, tzinfo=utc)),
        ),
    ]
