# Generated by Django 3.0.4 on 2020-05-25 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Comm', '0021_auto_20200518_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 25, 20, 51, 1, 604655, tzinfo=utc)),
        ),
    ]
