# Generated by Django 3.0.4 on 2020-05-25 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Comm', '0022_auto_20200525_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 25, 21, 4, 7, 315179, tzinfo=utc)),
        ),
    ]
