# Generated by Django 3.0.4 on 2020-05-31 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Comm', '0035_auto_20200529_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 18, 1, 42, 525783, tzinfo=utc)),
        ),
    ]
