# Generated by Django 3.0.4 on 2020-09-22 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdUserRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('prod_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('produserrel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Cart.ProdUserRel')),
                ('quantity', models.IntegerField(default=1)),
                ('nume', models.CharField(default='', max_length=50)),
                ('pret', models.FloatField(default=0)),
                ('gram', models.IntegerField(default=0)),
                ('inscr', models.CharField(default='', max_length=20)),
                ('img_url', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_order', models.DateField()),
            ],
            bases=('Cart.produserrel',),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('produserrel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Cart.ProdUserRel')),
                ('pret', models.FloatField()),
                ('nume', models.CharField(max_length=50)),
                ('img_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('Cart.produserrel',),
        ),
    ]
