# Generated by Django 3.0.4 on 2020-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='inscr',
            field=models.CharField(default='', max_length=30),
        ),
    ]
