# Generated by Django 3.0.4 on 2020-04-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='nume',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='pret',
            field=models.FloatField(default=0),
        ),
    ]
