# Generated by Django 3.0.4 on 2020-05-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_auto_20200425_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('produserrel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Cart.ProdUserRel')),
                ('pret', models.FloatField()),
                ('nume', models.CharField(max_length=50)),
            ],
            bases=('Cart.produserrel',),
        ),
    ]
