# Generated by Django 3.0.4 on 2020-06-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_cart_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='img_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
