# Generated by Django 3.0.4 on 2020-06-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_auto_20200623_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='img_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
