# Generated by Django 3.0.4 on 2020-05-25 20:51

import User.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('street_number', models.IntegerField(validators=[User.validators.phone, User.validators.poz])),
                ('bloc', models.IntegerField(validators=[User.validators.poz])),
                ('scara', models.IntegerField(validators=[User.validators.scara])),
                ('ap', models.IntegerField(validators=[User.validators.poz])),
            ],
        ),
    ]
