# Generated by Django 3.0.4 on 2020-05-25 21:12

import User.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default=0, max_length=10, validators=[User.validators.phone]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.IntegerField(validators=[User.validators.poz]),
        ),
    ]
