# Generated by Django 3.0.4 on 2020-05-25 21:14

import User.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20200526_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='scara',
            field=models.CharField(max_length=1, validators=[User.validators.scara]),
        ),
    ]
