# Generated by Django 3.0.4 on 2020-05-28 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20200529_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_user', to='User.Address'),
        ),
    ]
