# Generated by Django 3.0.4 on 2020-06-25 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_auto_20200531_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='addr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_user', to='User.Address'),
        ),
    ]
