# Generated by Django 3.0.4 on 2020-07-01 12:13

import User.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_auto_20200701_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ap',
            field=models.IntegerField(blank=True, null=True, validators=[User.validators.poz]),
        ),
        migrations.AlterField(
            model_name='address',
            name='bloc',
            field=models.IntegerField(blank=True, null=True, validators=[User.validators.poz]),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[User.validators.phone]),
        ),
        migrations.AlterField(
            model_name='address',
            name='scara',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[User.validators.scara]),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.IntegerField(blank=True, null=True, validators=[User.validators.poz]),
        ),
    ]
