# Generated by Django 3.0.4 on 2020-07-06 19:07

import User.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_auto_20200701_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[User.validators.poz]),
        ),
    ]
